### ISSUE TITLE
Measure Tip No Data Displaying

### ISSUE THREAD

**Issue by Tapdamonkey** [mannymerino/bci-calendar#22]
I am working with a Plan Table that has a Start Date, Promotion Name, End Date.  When Bringing in the Promotion Name into the measure field I receive a No Data Message, when bringing in a numerical value, the value shows, will this only work for numerical numbers and not text strings?

**Comment by mannymerino** [comment]
Hi @Tapdamonkey- thanks for using my calendar visual! Unfortunately the Measure Data field only supports numeric fields. Since it's primary purpose is to aggregate data by day, I don't see a way to support a text field here. My long-term roadmap does include researching the possibility of adding additional text values to go along with the Measure Data, but I don't have any timeline on when or if that will be implemented. Please let me know if you have any other questions or concerns. Thanks!

**Comment by Tapdamonkey** [comment]
Hey Manny!

Thanks for reaching out, so I was able to find a workout to get this to
work with text strings, if you start the description with a number “year”
and then have your text information the data actually displays pretty good,
Incase you didn’t know.  Thanks for the awesome visual!

Thanks
Sergio Zeno

**Comment by mannymerino** [comment]
That's great to hear! Glad you were able to figure out a workaround.
